//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OES_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Subject
    {
        public string User_ID { get; set; }
        public int Subject_ID { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
