//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsMark
    {
        public int CourseID { get; set; }
        public int SemesterID { get; set; }
        public string StudentID { get; set; }
        public int Midterm { get; set; }
        public int Final { get; set; }
        public int Practical { get; set; }
    }
}
