//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Answers
    {
        public int Exam_ID { get; set; }
        public string Student_ID { get; set; }
        public int Question_ID { get; set; }
        public Nullable<int> AnswerID { get; set; }
    }
}
