//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_EM
    {
        public int ECourse_ID { get; set; }
        public Nullable<int> Midterm { get; set; }
        public Nullable<int> Lab { get; set; }
        public Nullable<int> Quiz { get; set; }
        public Nullable<int> Final { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
