//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Teacher
    {
        public int CourseID { get; set; }
        public string Teacher_ID { get; set; }
        public string Semester { get; set; }
        public Nullable<double> Success_rate { get; set; }
    }
}
