//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Course_ID { get; set; }
        public string Course_Name { get; set; }
        public int Credit_Hours { get; set; }
        public string Course_Description { get; set; }
    }
}
