//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Course_Students = new HashSet<Course_Students>();
            this.Exams = new HashSet<Exam>();
            this.Semester_Courses = new HashSet<Semester_Courses>();
            this.ILOs = new HashSet<ILO>();
        }
    
        public int Course_ID { get; set; }
        public string Course_Name { get; set; }
        public int Credit_Hours { get; set; }
        public string Course_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Students> Course_Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Semester_Courses> Semester_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD
<<<<<<< HEAD
        public virtual ICollection<ILO> ILOs { get; set; }
=======
        public virtual ICollection<Topic> Topics { get; set; }
>>>>>>> 4987323c2b2daedd19efbc4d6b77dd89b5d82df6
=======
        public virtual ICollection<ILO> ILOs { get; set; }
>>>>>>> 7141463f045bd038efbd3c5a56cbd2b460e3aca3
    }
}
