//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Exam_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> Semster_ID { get; set; }
        public string Exam_Type { get; set; }
        public string Exam_Time { get; set; }
        public string Exam_Date { get; set; }
        public Nullable<int> number_Of_Students { get; set; }
        public Nullable<int> Exam_Period { get; set; }
        public string Exam_Notes { get; set; }
    }
}
