//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Bank
    {
        public int Question_ID { get; set; }
        public string Question_Text { get; set; }
        public string Expected_Time { get; set; }
        public Nullable<int> Difficulty_Level { get; set; }
        public Nullable<int> Question_Frequency { get; set; }
        public string Thinking_Skills { get; set; }
        public Nullable<int> Question_Mark { get; set; }
        public Nullable<int> ILO_ID { get; set; }
    }
}
