//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Answers
    {
        public string Std_Id { get; set; }
        public int Exam_Id { get; set; }
        public int Answer_Id { get; set; }
        public int Question_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Question_Answers Question_Answers { get; set; }
    }
}
