//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Answers
    {
<<<<<<< HEAD:EAS/EAS-DataBase/Students_Answers.cs
        public string Std_Id { get; set; }
        public int Exam_Id { get; set; }
        public int Answer_Id { get; set; }
        public int Question_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Question_Answers Question_Answers { get; set; }
=======
        public int Exam_ID { get; set; }
        public string Student_ID { get; set; }
        public int Question_ID { get; set; }
        public string Student_Answer { get; set; }
        public Nullable<bool> IsTrue { get; set; }
    
        public virtual Questions_Bank Questions_Bank { get; set; }
        public virtual Students_Exams Students_Exams { get; set; }
>>>>>>> 4987323c2b2daedd19efbc4d6b77dd89b5d82df6:EAS/EAS-DataBase/Student_Answers.cs
    }
}
