//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Exams
    {
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students_Exams()
        {
            this.Student_Answers = new HashSet<Student_Answers>();
        }
    
        public string Student_ID { get; set; }
        public int Exam_ID { get; set; }
        public Nullable<int> Exam_Result { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Answers> Student_Answers { get; set; }
=======
        public string Student_ID { get; set; }
        public int Exam_ID { get; set; }
        public Nullable<int> Exam_Result { get; set; }
>>>>>>> f0bbe600bddb1581549f1e674c7a777e5f078ec5
    }
}
