//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAS_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int Topic_ID { get; set; }
        public int Course_ID { get; set; }
        public string Topic_Description { get; set; }
        public Nullable<int> C_week { get; set; }
    }
}
